import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Montserrat } from "next/font/google";

const bodyFont = Montserrat({
  subsets: ['latin'],
  weight: ['400', '900']
})
import "./globals.css";
// import {Inter, Lalezar} from "next/font/google";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import { ThemeProvider } from "./components/context/ThemeContext";

// const inter = Inter({subsets: ['latin']});
// const lalezar = Lalezar({
//   subsets: ['arabic'],
//   weight: ['400']});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "HEXASHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className}`}>
        <ThemeProvider>
          <div className={"container"}>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
